version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: tournaments_db
    network_mode: "host"
    ports:
      - "3308:3306"